POST http://localhost:3000/api/register
Content-Type: application/json

{
  "first_name": "Idris",
  "last_name": "Olubisi",
  "email": "user@gmail.com",
  "password": "123456"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "123456"
}

###

GET http://localhost:3000/welcome
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjI4NzlmOGFlMDk0MGFkMmQ0NTkxN2RkIiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsImlhdCI6MTY1MzI5MzA2MSwiZXhwIjoxNjUzMjkzMDc2fQ.RyDABNHoZmrf7zMBIdscM9_Fp1UwXajnZ7Ib-1q4dWo

###

POST http://localhost:3000/api/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhiNmI3MDIxMTMzYTA2NzU2YjU4MWQiLCJ0b2tlbklkIjoiNjI4YjZiNzAyMTEzM2EwNjc1NmI1ODFmIiwiaWF0IjoxNjUzMzA0MTc2LCJleHAiOjE2NTMzMDQyMDZ9.rAHJyg1Kr1akPiurG_Il35iYlj2rV9Rl16bYMySvk8Y"
}

###

POST http://localhost:3000/api/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhiNmI3MDIxMTMzYTA2NzU2YjU4MWQiLCJ0b2tlbklkIjoiNjI4YjZiODEyMTEzM2EwNjc1NmI1ODIyIiwiaWF0IjoxNjUzMzA0MTkzLCJleHAiOjE2NTMzMDQyMjN9.DfHudlY8vifn5JUe17hhHHijkcXmjj0XRJOTnRf7PVQ"
}

###

POST http://localhost:3000/api/new-access-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhiNmI3MDIxMTMzYTA2NzU2YjU4MWQiLCJ0b2tlbklkIjoiNjI4YjZiYjQyMTEzM2EwNjc1NmI1ODMwIiwiaWF0IjoxNjUzMzA0MjQ0LCJleHAiOjE2NTMzMDQyNzR9.IefsbcdIERaZ1iB8upJy_J5FY97Hko2HUOkK10mVMTk"
}

###

POST http://localhost:3000/api/logout-all
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjhiNmI3MDIxMTMzYTA2NzU2YjU4MWQiLCJ0b2tlbklkIjoiNjI4YjZiOWMyMTEzM2EwNjc1NmI1ODJiIiwiaWF0IjoxNjUzMzA0MjIwLCJleHAiOjE2NTMzMDQyNTB9.-YUFkuC2SrXfy5e2pNQTpiMDIiGDmx3wgARnT76S8qA"
}